CREATE TABLE station_group (
    id bigint generated by default as identity primary key,
    display_name varchar(200) NOT NULL,
    display_order int NOT NULL,
    active boolean NOT NULL DEFAULT true
);

alter table station_group
    owner to postgres;